config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  root to: 'homes#top'

  get 'blogs/index' => 'blogs#index'
  resources :blogs

  resources :notifications, only: [:index, :destroy_all]
  delete '/notifications/destroy_all' => 'notifications#destroy_all'


  resources :posts do
    resource :likes, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  patch '/users/:id/hide' => 'users#hide', as: 'users_hide'
end

app/models/blog.rb
class Blog < ApplicationRecord
  
  belongs_to :user
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  before_action :current_user_blog, only: [:show, :edit, :update]

  def index
    @blogs = Blog.all.order("start_time")
  end

  def new
    @blog = Blog.new
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def create
    @blog = Blog.new(blog_params)
    @blog.save
    redirect_to blogs_path
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    @blog = Blog.find(params[:id])
    @blog.update(blog_params)
    redirect_to blogs_path
  end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    redirect_to blogs_path
  end

  private

  def blog_params
    params.require(:blog).permit(:title, :content, :start_time).merge(user_id: current_user.id)
  end

  def current_user_blog
    blog = Blog.find(params[:id])
    if blog.user != current_user
      redirect_to blogs_path
    end
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/edit.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-6 mx-auto">
    <%= form_with(model: @blog, local: true) do |f| %>
      <table>
        <tr height=100>
          <th><%= f.label :タイトル %> : </th>
          <td><%= f.text_field :title, class: "form-control" %></td>
        </tr>

        <tr height=100>
          <th><%= f.label :開始時間 %> : </th>
          <td><%= f.datetime_field :start_time, class: "form-control" %></td>
        </tr>

        <tr height=100>
          <th><%= f.label :詳細 %></th>
          <td><%= f.text_field :content, class: "form-control" %></td>
        </tr>


        <tr height=100>
          <th></th>
          <td><%= f.submit "更新", class: "btn btn-outline-dark btn-md text-center" %></td>
        </tr>

      </table>
    <% end %>
    </div>
  </div>
</div>

app/views/blogs/index.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-12">
      <h2>カレンダー</h2>
      <hr>
      <%= link_to "スケジュール追加", new_blog_path %>
      <hr>
      <table>
        <thead>
          <tr>
            <th>タイトル</th>
            <th>時間</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @blogs.each do |blog| %>
            <% if blog.user.id == current_user.id %>
              <tr>
                <td><%= blog.title %></td>
                <td><%= l blog.start_time %></td>
                <td><%= link_to '詳細', blog %> | </td>
                <td><%= link_to '編集', edit_blog_path(blog.id) %> | </td>
                <td><%= link_to '削除',blog_path(blog.id), method: :delete, data: { confirm: '本当に消してもいいですか？' } %></td>
              </tr>
              <% end %>
          <% end %>
        </tbody>
      </table>

      <br>

      <%= month_calendar events: @blogs do |date, blogs| %>
        <%= date.day %>

        <% blogs.each do |blog| %>
          <% if blog.user.id == current_user.id %>
            <div>
              <%= link_to blog.content, blog %>
            </div>
            <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/blogs/new.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-6 mx-auto">
    <%= form_with(model: @blog, local: true) do |f| %>
      <table>
        <tr height=100>
          <th><%= f.label :タイトル %> : </th>
          <td><%= f.text_field :title, class: "form-control" %></td>
        </tr>
      
        <tr height=100>
          <th><%= f.label :開始時間 %> : </th>
          <td><%= f.datetime_field :start_time, class: "form-control" %></td>
        </tr>
      
        <tr height=100>
          <th><%= f.label :詳細 %></th>
          <td><%= f.text_field :content, class: "form-control" %></td>
        </tr>
      
      
        <tr height=100>
          <th></th>
          <td><%= f.submit "投稿", class: "btn btn-outline-dark btn-md text-center" %></td>
        </tr>
      
      </table>
    <% end %>
    </div>
  </div>
</div>

app/views/blogs/show.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-6">
      <p>
        <strong>タイトル</strong>
        <%= @blog.title %>
      </p>

      <p>
        <strong>時間</strong>
        <%= l @blog.start_time %>
      </p>

      <p>
        <strong>内容</strong>
        <%= @blog.content %>
      </p>

      <%= link_to '編集', edit_blog_path(@blog) %> |
      <%= link_to '戻る', blogs_path %>
    </div>
  </div>
</div>