config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  root to: 'homes#top'

  get 'blogs/index' => 'blogs#index'
  resources :blogs

  resources :notifications, only: [:index, :destroy_all]
  delete '/notifications/destroy_all' => 'notifications#destroy_all'


  resources :posts do
    resource :likes, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  patch '/users/:id/hide' => 'users#hide', as: 'users_hide'
end

app/models/notification.rb
class Notification < ApplicationRecord

  #スコープ(新着順)
    default_scope->{order(created_at: :desc)}

    belongs_to :post, optional: true
    belongs_to :post_comment, optional: true
    belongs_to :visiter, class_name: 'User', foreign_key: 'visiter_id', optional: true
    belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController

  def index
    #current_userの投稿に紐づいた通知一覧
    @notifications = current_user.passive_notifications
    #@notificationの中でまだ確認していない(indexに一度も遷移していない)通知のみ
    @notifications.where(checked: false).each do |notification|
      notification.update_attributes(checked: true)
    end
  end

  def destroy_all
    #通知を全削除
    @notifications = current_user.passive_notifications.destroy_all
    redirect_to notifications_path
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper

  def unchecked_notifications
    @notifications = current_user.passive_notifications.where(checked: false)
  end
end

app/views/notifications/_notification.html.erb
<% visiter = notification.visiter %>
<% visited = notification.visited %>

<div class="col-md-5 mx-auto">
  <div class="card-body">
    <table class="table table-borderless">
      <tr>
        <td><%= attachment_image_tag notification.visiter, :profile_image, size: "80x80", fallback: "no-image.jpg", class: "rounded-circle" %></td>

        <% if notification.action == 'follow' %>
          <td class="pt-4">
            <%= link_to notification.visiter.name, user_path(visiter), style: "font-weight: bold;" %>さんがあなたをフォローしました
          </td>
        <% end %>
        
        <% if notification.action == 'comment' %>
          <td class="pt-4">
            <%= link_to notification.visiter.name, user_path(visiter), style: "font-weight: bold;" %>さんが
            <%= link_to "あなたの投稿", notification.post, style: "font-weight: bold;" %>にコメントしました<br>
            <span class="overflow-wrap"><%= PostComment.find_by(id: notification.post_comment_id)&.comment %></span>
          </td>
        <% end %>
        
        <% if notification.action == 'like' %>
          <td class="pt-4">
            <%= link_to notification.visiter.name, user_path(visiter), style: "font-weight: bold;" %>さんが
            <%= link_to 'あなたの投稿', notification.post, style: "font-weight: bold;" %>にいいねをしました
          </td>
        <% end %>
      </tr>

      <tr>
        <td class="pl-4"><%= time_ago_in_words(notification.created_at).upcase %>前</td>
      </tr>
    </table>
  </div>
</div>

app/views/notifications/index.html.erb
<%= link_to notifications_destroy_all_path, method: :delete do %>
  <i class="fas fa-trash" style="color: black;"></i>
  <h7 style="color: black;">全削除</h7>
<% end %>
  <hr>
<!--自分の投稿に対するいいね、コメントは通知に表示しない-->
<% notifications = @notifications.where.not(visiter_id: current_user.id) %>
  <% if @notifications.exists? %>
    <%= render @notifications %>
  <% else %>
    <p>通知はありません</p>
  <% end %>