config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  root to: 'homes#top'

  get 'blogs/index' => 'blogs#index'
  resources :blogs

  resources :notifications, only: [:index, :destroy_all]
  delete '/notifications/destroy_all' => 'notifications#destroy_all'


  resources :posts do
    resource :likes, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  patch '/users/:id/hide' => 'users#hide', as: 'users_hide'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  validates :name, presence: true, length: { minimum: 2, maximum: 20 }
  validates :encrypted_password, presence: true, length: { minimum: 6 }

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :blogs, dependent: :destroy
  attachment :profile_image

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  # 被フォロー関係を通じて参照→followed_idをフォローしている人

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 【class_name: "Relationship"】は省略可能
  has_many :followings, through: :relationships, source: :followed
  # 与フォロー関係を通じて参照→follower_idをフォローしている人

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  has_many :active_notifications, class_name: "Notification", foreign_key: "visiter_id", dependent: :destroy
  has_many :passive_notifications, class_name: "Notification", foreign_key: "visited_id", dependent: :destroy

  def create_notification_follow!(current_user)
    temp = Notification.where(["visiter_id = ? and visited_id = ? and action = ? ",current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end

  # 部分一致するユーザーネームがあれば、その結果がページに表示
  # https://www.for-engineer.life/entry/rails-search-form/
  def self.search(search) #self.はUser.を意味する
    if search
      where(['name LIKE ?', "%#{search}%"]) #検索とuserのnameの部分一致を表示。
    else
      all #全て表示させる
    end
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
    end
  end
  
  def active_for_authentication?
    super && (self.is_delete == false)
  end


end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController

  before_action :check_guest, only: [:create]

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  before_action :check_guest, only: [:update, :destroy]

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  
  before_action :reject_user, only: [:create]
  
  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
  
  protected
  
  def reject_user
    @user = User.find_by(email: params[:user][:email].downcase)
    if @user
      if (@user.valid_password?(params[:user][:password]) && (@user.active_for_authentication? == false))
        flash[:error] = "退会済みです。"
        redirect_to new_user_session_path
      end
    else
      flash[:error] = "必須項目を入力してください。"
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :ensure_current_user, only: [:edit, :update]

  def index
    @users = User.all.search(params[:search])
  end

  def show
    @user = User.find(params[:id])
  end

  def hide
    @user = User.find(params[:id])
    email = @user.email
    if email == 'guest@example.com'
      redirect_to root_path, notice: 'ゲストユーザーは編集・削除できません。'
    else
      @user.update(is_deleted: true)
      #ログアウトさせる
      reset_session
      redirect_to root_path, notice: "ありがとうございました。またのご利用を心よりお待ちしております。"
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "プロフィールを更新しました"
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def ensure_current_user
    user = User.find(params[:id])
    if user != current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow-count.html.erb
<%= link_to user_followings_path(user.id) do %>
  <span>
      フォロー数:<%= user.followings.count %>
  </span>
<% end %>

<%= link_to user_followers_path(user.id) do %>
  <span>
      フォロワー数:<%= user.followers.count %>
  </span>
<% end %>

app/views/users/_index.html.erb
<div class="container">
  <div class="row">
    <% if users.exists? %>
      <% users.each do |user| %>
        <div class="col-auto col-md-3 mt-5 pl-5">
          <span style="font-family: cursive;">
            <%= link_to user_path(user) do %>
              <%= attachment_image_tag user, :profile_image, fallback: "no-image.jpg", size: "100x100", class: "rounded-circle" %><br>
            <% end %>
            <span class="pl-2">Name: <%= user.name %></span><br>
            <span  class="follow-btn_<%= user.id %>"><%= render 'users/info', user: user %></span>
          </span>
        </div>
      <% end %>

    <% else %>
      <p>ユーザーがいません</p>
    <% end %>
  </div>
</div>

app/views/users/_info.html.erb
<% unless user == current_user %>
  <% if current_user.following?(user) %>
    <%= link_to "フォロー解除", user_relationships_path(user.id), method: :delete, class: "btn btn-outline-dark btn-sm", remote: true %>
  <% else %>
    <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-outline-dark btn-sm", remote: true %>
  <% end %>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-6 mx-auto mt-5">
      <%= form_with model: @user, local:true do |f| %>

        <%= f.label :プロフィール画像 %><br>
        <%= f.attachment_field :profile_image %><br>
        <br>

        <%= f.label :名前 %><br>
        <%= f.text_field :name %><br>
        <br>

        <%= f.label :プロフィール %><br>
        <%= f.text_area :introduction %><br>
        <br>

        <%= f.submit '更新', class:"btn btn-outline-dark" %>

        <% if user_signed_in? && @user.id == current_user.id %>
          <%= link_to "退会", users_hide_path(current_user), method: :patch, "data-confirm" => "本当に退会しますか？", class: "btn btn-outline-danger" %>
        <% end %>

      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<%= render 'index', users: @users %>

app/views/users/show.html.erb
<div class="container">
    <div class ="row">
        <div class="col-md-2">
           <p><%= attachment_image_tag @user, :profile_image, fallback: "no-image.jpg",size: "150x150", class: "rounded-circle" %></p>
           <p class="follow-btn_<%= @user.id %>"><%= render 'users/info', user: @user %></p>
            <% if @user.id == current_user.id %>
               <p><%= link_to "編集", edit_user_path(@user), class: "btn btn-outline-dark btn-md ml-5" %></p>
            <% end %>
        </div>

        <div class="col-md-6 mt-3">
            <span class="follow-count_<%= @user.id %>"><%= render 'users/follow-count', user: @user %></span><br><hr>
            <span style="font-family: cursive;">Name: <%= @user.name %></span><br><hr>
            <span style="font-family: cursive;">Profile: <%= @user.introduction %></span>
        </div>
    </div>
    
    <div class="row">
      <% @user.posts.reverse.each do |post| %>
        <div class="col-lg-4 col-md-6 mt-5">
          <div class="slider">
            <% if post.images.attached? %>
              <% post.images.each do |image| %>
                <%= link_to post_path(post) do %>
                  <%= image_tag image, size: "400x300" %>
                <% end %>
              <% end %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
</div>