config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  root to: 'homes#top'

  get 'blogs/index' => 'blogs#index'
  resources :blogs

  resources :notifications, only: [:index, :destroy_all]
  delete '/notifications/destroy_all' => 'notifications#destroy_all'


  resources :posts do
    resource :likes, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  patch '/users/:id/hide' => 'users#hide', as: 'users_hide'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BikeRoad2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
  </head>

    <% if flash[:notice] %>
      <div class="alert alert-primary" role="aleat"><strong><%= notice %></strong></div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-denger" role="aleat"><strong><%= alert %></strong></div>
    <% end %>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <%= link_to root_path, class: 'text-dark' do %>
            <h2 style="font-family: cursive;">Bike道</h2>
          <% end %>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto gnavi">

              <% if user_signed_in? %>

                <li class="fadeIn">
                  <%= link_to "投稿一覧", posts_path, class: "nav-link text-dark" %>
                </li>

                <li class="fadeIn">
                  <%= link_to "ユーザー一覧", users_path, class: "nav-link text-dark" %>
                </li>

                <li class="fadeIn">
                  <%= link_to "新規投稿", new_post_path, class: "nav-link text-dark" %>
                </li>

                <li class="fadeIn">
                  <%= link_to "マイページ", user_path(current_user.id), class: "nav-link text-dark" %>
                </li>

                <% if unchecked_notifications.any? %>
                  <i class="fa fa-circle" style="color: gold;"></i>
                <% end %>
                <li class="fadeIn">
                  <%= link_to "通知", notifications_path, class: 'nav-link text-dark' %>
                </li>

                <li class="fadeIn">
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link text-dark" %>
                </li>

                <li class="fadeIn">
                  <%= link_to "", blogs_path, class: 'nav-link text-dark far fa-calendar-alt mt-1' %>
                </li>

                <li class="mt-1 ml-5 fadeIn">
                  <%= form_tag(users_path, :method => "get") do %>
                    <%= text_field_tag :search, '', placeholder: 'ユーザー名' %>
                    <%= submit_tag "検索" ,:name => nil ,class: "btn btn-outline-dark btn-sm"%>
                  <% end %>
                </li>

              <% else %>

                <li class="fadeIn">
                  <%= link_to "新規登録", new_user_registration_path, class: "nav-link text-dark" %>
                </li>

                <li class="fadeIn">
                  <%= link_to "ログイン", new_user_session_path, class: "nav-link text-dark" %>
                </li>

                <li class="fadeIn">
                  <%= link_to "ゲストログイン", users_guest_sign_in_path, class: 'nav-link text-dark', method: :post %>
                </li>

              <% end %>

            </ul>
          </div>

        </div>
      </nav>
    </header>
    <hr>
    <%= yield %>
  </body>
</html>